### PR TITLE
Color branches

### PR DESCRIPTION
**Pull request by d-callan**
this one adds:
1. the ability to change the default color of branches
2. ability to highlight/ color branches which are related to your highlighted/ colored nodes (starting w monophyletic relationships)
3. the ability to find node guids by predicate

and modifies:
1. the color menu, by replacing the highlight nodes toggle w a few dedicated highlighting examples

### CODE REVIEW

**Comment by d-callan** [comment]
@reagank 
fwiw, i wasnt super thrilled at the idea to add a dedicated example of highlighting that focused on specific, predefined nodes/ taxa. id have rather added an option like 'highlight on search', but then i realized the search didnt seem to be working for me, and decided it was out of scope for now.

**Comment by d-callan** [comment]
just curious for an update here @reagank

**Review by reagank — APPROVED** [review]

**Comment by reagank** [comment]
@d-callan Thanks very much for this. Sorry it took so long to get it reviewed and merged.

**Comment by d-callan** [comment]
Thanks for merging :) I might have one more for you, though with an API change. We (VEuPathDB) did an internal review of my changes in preparation for putting this into production and some good suggestions came out of it.

**Pull request merged**
